export default {
	plugins: ['@projectwallace/stylelint-plugin'],
	rules: {
		'projectwallace/no-invalid-z-index': true,
		'projectwallace/no-unknown-container-names': true,
		'no-unknown-custom-properties': true,
		'projectwallace/no-missing-if-else': true,
		'projectwallace/no-unreachable-if-branches': true,
		'projectwallace/no-useless-if': true,
		'projectwallace/no-unreachable-media-conditions': true,
		'projectwallace/no-duplicate-anchor-names': true,
		'projectwallace/no-duplicate-container-names': true,
		'projectwallace/no-duplicate-custom-properties': true,
		'projectwallace/no-duplicate-keyframes': true,
		'projectwallace/no-duplicate-registered-properties': true,
		'block-no-empty': [true, { ignore: ['comments'] }],
		'keyframe-declaration-no-important': true,
		'projectwallace/no-useless-custom-property-assignment': true,
		'projectwallace/no-unused-custom-properties': true,
		'projectwallace/no-unused-container-names': true,
		'projectwallace/no-unused-keyframes': true,
		'projectwallace/no-unused-layers': true,
		'projectwallace/no-static-media-queries': true,
		'projectwallace/no-static-container-queries': true,
		'projectwallace/no-pseudo-elements-in-is-where': true,
	},
}
