export default {
	plugins: ['@projectwallace/stylelint-plugin'],
	rules: {
		'projectwallace/max-atrules': [250, { severity: 'warning' }],
		'projectwallace/max-declarations': [5000, { severity: 'warning' }],
		'projectwallace/max-rules': [1000, { severity: 'warning' }],
		'projectwallace/max-selectors': [2500, { severity: 'warning' }],
		'projectwallace/max-unique-color-formats': [4, { severity: 'warning' }],
		'projectwallace/max-average-declarations-per-rule': [6, { severity: 'warning' }],
		'projectwallace/max-average-selector-complexity': [3, { severity: 'warning' }],
		'projectwallace/max-average-selectors-per-rule': [3, { severity: 'warning' }],
		'projectwallace/max-average-selector-specificity': [[0.02, 2.5, 1], { severity: 'warning' }],
		'projectwallace/max-declarations-per-rule': [15, { severity: 'warning' }],
		'projectwallace/max-important-ratio': [0.1, { severity: 'warning' }],
		'max-nesting-depth': [3, { severity: 'warning' }],
		'projectwallace/max-selector-complexity': [15, { severity: 'warning' }],
		'projectwallace/max-selectors-per-rule': [10, { severity: 'warning' }],
		'selector-max-specificity': ['0,5,0', { severity: 'warning' }],
		'projectwallace/max-unique-keyframes': [8, { severity: 'warning' }],
		'projectwallace/max-unique-media-queries': [12, { severity: 'warning' }],
		'projectwallace/max-unique-supports-queries': [8, { severity: 'warning' }],
		'projectwallace/max-unique-units': [10, { severity: 'warning' }],
		'projectwallace/max-unique-z-indexes': [8, { severity: 'warning' }],
		'projectwallace/min-declaration-uniqueness-ratio': [0.5, { severity: 'warning' }],
		'projectwallace/min-selector-uniqueness-ratio': [0.66, { severity: 'warning' }],
		'projectwallace/no-anonymous-layers': true,
		'projectwallace/no-atrule-browserhacks': true,
		'at-rule-no-vendor-prefix': true,
		'property-no-vendor-prefix': [true, { ignoreProperties: ['-webkit-text-fill-color'] }],
		'selector-no-vendor-prefix': [
			true,
			{ ignoreSelectors: [/^::-webkit-scrollbar/, ':-webkit-autofill'] },
		],
		'value-no-vendor-prefix': true,
		'projectwallace/no-property-browserhacks': true,
		'projectwallace/no-property-shorthand': [
			true,
			{
				disallow: ['animation', 'background', 'flex', 'font', 'grid', 'transition'],
				ignore: ['single-value'],
			},
		],
		'projectwallace/max-comments': [64, { ignoreCopyrightComments: true, severity: 'warning' }],
		'projectwallace/max-spacing-resets': [16, { severity: 'warning' }],
	},
}
