export default {
	plugins: ['@projectwallace/stylelint-plugin'],
	rules: {
		'projectwallace/max-atrules': 250,
		'projectwallace/max-declarations': 5000,
		'projectwallace/max-rules': 1000,
		'projectwallace/max-selectors': 2500,
		'projectwallace/max-unique-color-formats': 4,
		'projectwallace/max-average-declarations-per-rule': 6,
		'projectwallace/max-average-selector-complexity': 3,
		'projectwallace/max-average-selectors-per-rule': 3,
		'projectwallace/max-average-specificity': [0.02, 2.5, 1],
		'projectwallace/max-declarations-per-rule': 15,
		'projectwallace/max-important-ratio': 0.1,
		'projectwallace/max-selector-complexity': 15,
		'projectwallace/max-selectors-per-rule': 10,
		'projectwallace/max-selector-specificity': [0, 5, 0],
		'projectwallace/max-unique-keyframes': 8,
		'projectwallace/max-unique-media-queries': 12,
		'projectwallace/max-unique-supports-queries': 8,
		'projectwallace/max-unique-units': 10,
		'projectwallace/max-unique-z-indexes': 8,
		'projectwallace/min-declaration-uniqueness-ratio': 0.5,
		'projectwallace/min-selector-uniqueness-ratio': 0.66,
		'projectwallace/no-anonymous-layers': true,
		'projectwallace/no-atrule-browserhacks': true,
		'projectwallace/no-prefixed-atrules': true,
		'projectwallace/no-prefixed-properties': [true, { ignore: ['-webkit-text-fill-color'] }],
		'projectwallace/no-prefixed-selectors': [
			true,
			{ ignore: [/^::-webkit-scrollbar/, ':-webkit-autofill'] },
		],
		'projectwallace/no-prefixed-values': true,
		'projectwallace/no-property-browserhacks': true,
		'projectwallace/no-property-shorthand': true,
		'projectwallace/max-spacing-resets': 16,
	},
}
