export default {
	plugins: ['@projectwallace/stylelint-plugin'],
	rules: {
		'projectwallace/max-lines-of-code': 10000,
		'projectwallace/max-selector-complexity': 15,
		'projectwallace/no-anonymous-layers': true,
		'projectwallace/no-property-browserhacks': true,
		'projectwallace/no-property-shorthand': true,
		'projectwallace/no-static-container-query': true,
		'projectwallace/no-static-media-query': true,
		'projectwallace/no-unknown-container-names': true,
		'projectwallace/no-unknown-custom-property': true,
		'projectwallace/no-unreachable-media-conditions': true,
		'projectwallace/no-unused-container-names': true,
		'projectwallace/no-unused-custom-properties': true,
		'projectwallace/no-unused-layers': true,
		'projectwallace/no-useless-custom-property-assignment': true,
		'projectwallace/no-duplicate-data-urls': true,
		'projectwallace/no-invalid-z-index': true,
		'projectwallace/max-file-size': 200000,
		'projectwallace/max-embedded-content-size': 10000,
		'projectwallace/max-comment-size': [2500, { ignoreCopyrightComments: true }],
		'projectwallace/max-average-selectors-per-rule': 3,
		'projectwallace/max-average-declarations-per-rule': 6,
		'projectwallace/max-average-selector-complexity': 3,
		'projectwallace/max-important-ratio': 0.1,
		'projectwallace/max-unique-colors': 128,
		'projectwallace/max-unique-font-families': 4,
		'projectwallace/max-unique-font-sizes': 16,
		'projectwallace/max-unique-units': 10,
		'projectwallace/min-selector-uniqueness-ratio': 0.66,
		'projectwallace/min-declaration-uniqueness-ratio': 0.5,
		'projectwallace/max-average-specificity': [0.02, 2.5, 1],
		'projectwallace/max-selectors-per-rule': 10,
		'projectwallace/max-declarations-per-rule': 15,
	},
}
