export default {
	plugins: ['@projectwallace/stylelint-plugin'],
	rules: {
		'projectwallace/max-rules': [1000, { severity: 'warning' }],
		'projectwallace/max-atrules': [250, { severity: 'warning' }],
		'projectwallace/max-selectors': [2500, { severity: 'warning' }],
		'projectwallace/max-declarations': [5000, { severity: 'warning' }],
		'projectwallace/max-lines-of-code': [10_000, { severity: 'warning' }],
		'max-nesting-depth': [3, { severity: 'warning' }],
		'projectwallace/max-selector-complexity': [15, { severity: 'warning' }],
		'selector-max-specificity': ['0,5,0', { severity: 'warning' }],
		'projectwallace/no-anonymous-layers': true,
		'projectwallace/no-atrule-browserhacks': true,
		'at-rule-no-vendor-prefix': true,
		'property-no-vendor-prefix': [true, { ignoreProperties: ['-webkit-text-fill-color'] }],
		'selector-no-vendor-prefix': [
			true,
			{ ignoreSelectors: [/^::-webkit-scrollbar/, ':-webkit-autofill'] },
		],
		'value-no-vendor-prefix': true,
		'projectwallace/no-property-browserhacks': true,
		'projectwallace/no-property-shorthand': [
			true,
			{
				disallow: ['animation', 'background', 'flex', 'font', 'grid', 'transition'],
				ignore: ['single-value'],
			},
		],
		'projectwallace/no-pseudo-elements-in-is-where': true,
		'projectwallace/no-static-container-queries': true,
		'projectwallace/no-static-media-queries': true,
		'projectwallace/no-unknown-container-names': true,
		'no-unknown-custom-properties': true,
		'projectwallace/no-missing-if-else': true,
		'projectwallace/no-unreachable-if-branches': true,
		'projectwallace/no-useless-if': true,
		'projectwallace/no-unreachable-media-conditions': true,
		'projectwallace/no-unused-container-names': true,
		'projectwallace/no-unused-custom-properties': true,
		'projectwallace/no-unused-keyframes': true,
		'projectwallace/no-unused-layers': true,
		'projectwallace/no-useless-custom-property-assignment': true,
		'projectwallace/no-duplicate-anchor-names': true,
		'projectwallace/no-duplicate-container-names': true,
		'projectwallace/no-duplicate-custom-properties': true,
		'projectwallace/no-duplicate-data-urls': true,
		'projectwallace/no-duplicate-keyframes': true,
		'projectwallace/no-duplicate-registered-properties': true,
		'block-no-empty': [true, { ignore: ['comments'] }],
		'keyframe-declaration-no-important': true,
		'projectwallace/no-invalid-z-index': true,
		'projectwallace/no-value-browserhacks': true,
		'projectwallace/max-file-size': [200_000, { severity: 'warning' }],
		'projectwallace/max-embedded-content-size': [10_000, { severity: 'warning' }],
		'projectwallace/max-comment-size': [
			2500,
			{ ignoreCopyrightComments: true, severity: 'warning' },
		],
		'projectwallace/max-comments': [64, { ignoreCopyrightComments: true, severity: 'warning' }],
		'projectwallace/max-average-selectors-per-rule': [3, { severity: 'warning' }],
		'projectwallace/max-average-declarations-per-rule': [6, { severity: 'warning' }],
		'projectwallace/max-average-selector-complexity': [3, { severity: 'warning' }],
		'projectwallace/max-important-ratio': [0.1, { severity: 'warning' }],
		'projectwallace/max-unique-box-shadows': [8, { severity: 'warning' }],
		'projectwallace/max-unique-text-shadows': [4, { severity: 'warning' }],
		'projectwallace/max-unique-color-formats': [4, { severity: 'warning' }],
		'projectwallace/max-unique-colors': [128, { severity: 'warning' }],
		'projectwallace/max-unique-animation-functions': [4, { severity: 'warning' }],
		'projectwallace/max-unique-durations': [8, { severity: 'warning' }],
		'projectwallace/max-unique-font-families': [4, { severity: 'warning' }],
		'projectwallace/max-unique-font-sizes': [16, { severity: 'warning' }],
		'projectwallace/max-unique-line-heights': [12, { severity: 'warning' }],
		'projectwallace/max-unique-z-indexes': [8, { severity: 'warning' }],
		'projectwallace/max-unique-media-queries': [12, { severity: 'warning' }],
		'projectwallace/max-unique-keyframes': [8, { severity: 'warning' }],
		'projectwallace/max-unique-gradients': [8, { severity: 'warning' }],
		'projectwallace/max-unique-supports-queries': [8, { severity: 'warning' }],
		'projectwallace/max-unique-units': [10, { severity: 'warning' }],
		'projectwallace/min-selector-uniqueness-ratio': [0.66, { severity: 'warning' }],
		'projectwallace/min-declaration-uniqueness-ratio': [0.5, { severity: 'warning' }],
		'projectwallace/max-average-selector-specificity': [[0.02, 2.5, 1], { severity: 'warning' }],
		'projectwallace/max-selectors-per-rule': [10, { severity: 'warning' }],
		'projectwallace/max-declarations-per-rule': [15, { severity: 'warning' }],
		'projectwallace/max-spacing-resets': [16, { severity: 'warning' }],
	},
}
